http:
  allow_http: true
  port: 7015
  use_gzip: true

# todo the worker isn't doing anything for me at the moment
#workers:
#  messenger_consume:
#    cmd: ['symfony', 'console', 'messenger:consume', '--all', '--sleep', '10']
#    watch: ['config', 'src', 'templates']
