<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260409090433 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Flip package and version installations association direction';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            ALTER TABLE package_installations DROP CONSTRAINT fk_69b10efbf44cabff
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE package_installations DROP CONSTRAINT package_downloads_pkey
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE package_installations ADD id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE package_installations ADD PRIMARY KEY (id)
        SQL);

        $this->addSql(<<<'SQL'
            ALTER TABLE package ADD installations_id INT DEFAULT NULL
        SQL);
        $this->addSql(<<<'SQL'
            UPDATE package SET installations_id = package_installations.id
            FROM package_installations
            WHERE package_installations.package_id = package.id
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE package ALTER installations_id SET NOT NULL
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE package ADD CONSTRAINT FK_DE6867952B6BB138 FOREIGN KEY (installations_id) REFERENCES package_installations (id) ON DELETE CASCADE NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX UNIQ_DE6867952B6BB138 ON package (installations_id)
        SQL);

        $this->addSql(<<<'SQL'
            ALTER TABLE package_installations DROP package_id
        SQL);

        $this->addSql(<<<'SQL'
            ALTER TABLE version_installations DROP CONSTRAINT fk_67c4df0d4bbc2705
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE version_installations DROP CONSTRAINT version_downloads_pkey
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE version_installations ADD id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE version_installations ADD PRIMARY KEY (id)
        SQL);

        $this->addSql(<<<'SQL'
            ALTER TABLE version ADD installations_id INT DEFAULT NULL
        SQL);
        $this->addSql(<<<'SQL'
            UPDATE version SET installations_id = version_installations.id
            FROM version_installations
            WHERE version_installations.version_id = version.id
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE version ALTER installations_id SET NOT NULL
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE version ADD CONSTRAINT FK_BF1CD3C32B6BB138 FOREIGN KEY (installations_id) REFERENCES version_installations (id) ON DELETE CASCADE NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX UNIQ_BF1CD3C32B6BB138 ON version (installations_id)
        SQL);

        $this->addSql(<<<'SQL'
            ALTER TABLE version_installations DROP version_id
        SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            ALTER TABLE package_installations ADD package_id INT DEFAULT NULL
        SQL);
        $this->addSql(<<<'SQL'
            UPDATE package_installations SET package_id = package.id
            FROM package
            WHERE package.installations_id = package_installations.id
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE package_installations ALTER package_id SET NOT NULL
        SQL);

        $this->addSql(<<<'SQL'
            ALTER TABLE package DROP CONSTRAINT FK_DE6867952B6BB138
        SQL);
        $this->addSql(<<<'SQL'
            DROP INDEX UNIQ_DE6867952B6BB138
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE package DROP installations_id
        SQL);

        $this->addSql(<<<'SQL'
            ALTER TABLE package_installations DROP CONSTRAINT package_installations_pkey
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE package_installations DROP id
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE package_installations ADD CONSTRAINT fk_69b10efbf44cabff FOREIGN KEY (package_id) REFERENCES package (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE package_installations ADD PRIMARY KEY (package_id)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER INDEX package_installations_pkey RENAME TO package_downloads_pkey
        SQL);

        $this->addSql(<<<'SQL'
            ALTER TABLE version_installations ADD version_id INT DEFAULT NULL
        SQL);
        $this->addSql(<<<'SQL'
            UPDATE version_installations SET version_id = version.id
            FROM version
            WHERE version.installations_id = version_installations.id
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE version_installations ALTER version_id SET NOT NULL
        SQL);

        $this->addSql(<<<'SQL'
            ALTER TABLE version DROP CONSTRAINT FK_BF1CD3C32B6BB138
        SQL);
        $this->addSql(<<<'SQL'
            DROP INDEX UNIQ_BF1CD3C32B6BB138
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE version DROP installations_id
        SQL);

        $this->addSql(<<<'SQL'
            ALTER TABLE version_installations DROP CONSTRAINT version_installations_pkey
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE version_installations DROP id
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE version_installations ADD CONSTRAINT fk_67c4df0d4bbc2705 FOREIGN KEY (version_id) REFERENCES version (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE version_installations ADD PRIMARY KEY (version_id)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER INDEX version_installations_pkey RENAME TO version_downloads_pkey
        SQL);
    }
}
