<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20250820135523 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Rename tags to keywords';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE keyword (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(191) NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE version_keyword (version_id INT NOT NULL, keyword_id INT NOT NULL, PRIMARY KEY(version_id, keyword_id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_A65A946F4BBC2705 ON version_keyword (version_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_A65A946F115D4552 ON version_keyword (keyword_id)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE version_keyword ADD CONSTRAINT FK_A65A946F4BBC2705 FOREIGN KEY (version_id) REFERENCES version (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE version_keyword ADD CONSTRAINT FK_A65A946F115D4552 FOREIGN KEY (keyword_id) REFERENCES keyword (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE version_tag DROP CONSTRAINT fk_187c97b84bbc2705
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE version_tag DROP CONSTRAINT fk_187c97b8bad26311
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE version_tag
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE tag
        SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE version_tag (version_id INT NOT NULL, tag_id INT NOT NULL, PRIMARY KEY(version_id, tag_id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX idx_187c97b8bad26311 ON version_tag (tag_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX idx_187c97b84bbc2705 ON version_tag (version_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE tag (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(191) NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE version_tag ADD CONSTRAINT fk_187c97b84bbc2705 FOREIGN KEY (version_id) REFERENCES version (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE version_tag ADD CONSTRAINT fk_187c97b8bad26311 FOREIGN KEY (tag_id) REFERENCES tag (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE version_keyword DROP CONSTRAINT FK_A65A946F4BBC2705
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE version_keyword DROP CONSTRAINT FK_A65A946F115D4552
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE keyword
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE version_keyword
        SQL);
    }
}
