<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260519130834 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Extract readme into a separate metadata_files entity';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE metadata_files (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                readme TEXT DEFAULT NULL,
                metadata_id INT DEFAULT NULL,
                PRIMARY KEY (id)
            )
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE metadata ADD files_id INT DEFAULT NULL
        SQL);
        $this->addSql(<<<'SQL'
            INSERT INTO metadata_files (readme, metadata_id) SELECT readme, id FROM metadata
        SQL);
        $this->addSql(<<<'SQL'
            UPDATE metadata SET files_id = metadata_files.id
            FROM metadata_files
            WHERE metadata_files.metadata_id = metadata.id
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE metadata_files DROP metadata_id
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE metadata DROP readme
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE metadata ALTER files_id SET NOT NULL
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE metadata ADD CONSTRAINT FK_4F143414A3E65B2F FOREIGN KEY (files_id) REFERENCES metadata_files (id) ON DELETE CASCADE NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX UNIQ_4F143414A3E65B2F ON metadata (files_id)
        SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            ALTER TABLE metadata ADD readme TEXT DEFAULT NULL
        SQL);
        $this->addSql(<<<'SQL'
            UPDATE metadata SET readme = metadata_files.readme
            FROM metadata_files
            WHERE metadata_files.id = metadata.files_id
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE metadata DROP CONSTRAINT FK_4F143414A3E65B2F
        SQL);
        $this->addSql(<<<'SQL'
            DROP INDEX UNIQ_4F143414A3E65B2F
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE metadata DROP files_id
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE metadata_files
        SQL);
    }
}
