<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260701083050 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create distribution table';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE distribution (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              reference VARCHAR(255) NOT NULL,
              type VARCHAR(255) NOT NULL,
              source TEXT DEFAULT NULL,
              released_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              resolved_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              last_modified_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              metadata_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_A4483781DC9EE959 ON distribution (metadata_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX UNIQ_A4483781DC9EE959AEA349138CDE5729 ON distribution (metadata_id, reference, type)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              distribution
            ADD
              CONSTRAINT FK_A4483781DC9EE959 FOREIGN KEY (metadata_id) REFERENCES metadata (id) NOT DEFERRABLE
        SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            ALTER TABLE distribution DROP CONSTRAINT FK_A4483781DC9EE959
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE distribution
        SQL);
    }
}
