<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20250606212853 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Recreate version link tables';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE version_conflict_link (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, linked_package_name VARCHAR(191) NOT NULL, linked_version_constraint TEXT NOT NULL, version_id INT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_AD52D6C4BBC2705 ON version_conflict_link (version_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE version_dev_require_link (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, linked_package_name VARCHAR(191) NOT NULL, linked_version_constraint TEXT NOT NULL, version_id INT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_98F2E46E4BBC2705 ON version_dev_require_link (version_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE version_provide_link (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, linked_package_name VARCHAR(191) NOT NULL, linked_version_constraint TEXT NOT NULL, version_id INT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_150EC10C4BBC2705 ON version_provide_link (version_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE version_replace_link (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, linked_package_name VARCHAR(191) NOT NULL, linked_version_constraint TEXT NOT NULL, version_id INT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_87F1B96A4BBC2705 ON version_replace_link (version_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE version_require_link (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, linked_package_name VARCHAR(191) NOT NULL, linked_version_constraint TEXT NOT NULL, version_id INT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_7A1CAAB14BBC2705 ON version_require_link (version_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE version_suggest_link (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, linked_package_name VARCHAR(191) NOT NULL, linked_version_constraint TEXT NOT NULL, version_id INT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_DE9B76884BBC2705 ON version_suggest_link (version_id)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE version_conflict_link ADD CONSTRAINT FK_AD52D6C4BBC2705 FOREIGN KEY (version_id) REFERENCES version (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE version_dev_require_link ADD CONSTRAINT FK_98F2E46E4BBC2705 FOREIGN KEY (version_id) REFERENCES version (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE version_provide_link ADD CONSTRAINT FK_150EC10C4BBC2705 FOREIGN KEY (version_id) REFERENCES version (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE version_replace_link ADD CONSTRAINT FK_87F1B96A4BBC2705 FOREIGN KEY (version_id) REFERENCES version (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE version_require_link ADD CONSTRAINT FK_7A1CAAB14BBC2705 FOREIGN KEY (version_id) REFERENCES version (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE version_suggest_link ADD CONSTRAINT FK_DE9B76884BBC2705 FOREIGN KEY (version_id) REFERENCES version (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE dev_require_link DROP CONSTRAINT fk_47a9dc2b4bbc2705
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE conflict_link DROP CONSTRAINT fk_ca65041a4bbc2705
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE suggest_link DROP CONSTRAINT fk_d4deadf74bbc2705
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE require_link DROP CONSTRAINT fk_705971ce4bbc2705
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE replace_link DROP CONSTRAINT fk_8db462154bbc2705
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE provide_link DROP CONSTRAINT fk_1f4b1a734bbc2705
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE dev_require_link
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE conflict_link
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE suggest_link
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE require_link
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE replace_link
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE provide_link
        SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE dev_require_link (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, version_id INT NOT NULL, package_name VARCHAR(191) NOT NULL, package_version TEXT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX idx_47a9dc2b4bbc2705 ON dev_require_link (version_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE conflict_link (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, version_id INT NOT NULL, package_name VARCHAR(191) NOT NULL, package_version TEXT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX idx_ca65041a4bbc2705 ON conflict_link (version_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE suggest_link (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, version_id INT NOT NULL, package_name VARCHAR(191) NOT NULL, package_version TEXT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX idx_d4deadf74bbc2705 ON suggest_link (version_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE require_link (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, version_id INT NOT NULL, package_name VARCHAR(191) NOT NULL, package_version TEXT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX idx_705971ce4bbc2705 ON require_link (version_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE replace_link (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, version_id INT NOT NULL, package_name VARCHAR(191) NOT NULL, package_version TEXT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX idx_8db462154bbc2705 ON replace_link (version_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE provide_link (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, version_id INT NOT NULL, package_name VARCHAR(191) NOT NULL, package_version TEXT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX idx_1f4b1a734bbc2705 ON provide_link (version_id)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE dev_require_link ADD CONSTRAINT fk_47a9dc2b4bbc2705 FOREIGN KEY (version_id) REFERENCES version (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE conflict_link ADD CONSTRAINT fk_ca65041a4bbc2705 FOREIGN KEY (version_id) REFERENCES version (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE suggest_link ADD CONSTRAINT fk_d4deadf74bbc2705 FOREIGN KEY (version_id) REFERENCES version (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE require_link ADD CONSTRAINT fk_705971ce4bbc2705 FOREIGN KEY (version_id) REFERENCES version (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE replace_link ADD CONSTRAINT fk_8db462154bbc2705 FOREIGN KEY (version_id) REFERENCES version (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE provide_link ADD CONSTRAINT fk_1f4b1a734bbc2705 FOREIGN KEY (version_id) REFERENCES version (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE version_conflict_link DROP CONSTRAINT FK_AD52D6C4BBC2705
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE version_dev_require_link DROP CONSTRAINT FK_98F2E46E4BBC2705
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE version_provide_link DROP CONSTRAINT FK_150EC10C4BBC2705
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE version_replace_link DROP CONSTRAINT FK_87F1B96A4BBC2705
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE version_require_link DROP CONSTRAINT FK_7A1CAAB14BBC2705
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE version_suggest_link DROP CONSTRAINT FK_DE9B76884BBC2705
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE version_conflict_link
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE version_dev_require_link
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE version_provide_link
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE version_replace_link
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE version_require_link
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE version_suggest_link
        SQL);
    }
}
