<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260323085127 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add index to version keyword association';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            ALTER TABLE version_keyword DROP CONSTRAINT fk_a65a946f115d4552
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE version_keyword DROP CONSTRAINT fk_a65a946f4bbc2705
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE version_keyword DROP CONSTRAINT version_keyword_pkey
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE version_keyword ADD id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE version_keyword ADD index INT DEFAULT NULL
        SQL);
        $this->addSql(<<<'SQL'
            UPDATE version_keyword
            SET index = sub.row_num - 1
            FROM (
                SELECT version_id, keyword_id, ROW_NUMBER() OVER (PARTITION BY version_id ORDER BY keyword_id) AS row_num
                FROM version_keyword
            ) sub
            WHERE version_keyword.version_id = sub.version_id AND version_keyword.keyword_id = sub.keyword_id
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE version_keyword ALTER COLUMN index SET NOT NULL
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
                version_keyword
            ADD
                CONSTRAINT FK_A65A946F115D4552 FOREIGN KEY (keyword_id) REFERENCES keyword (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
                version_keyword
            ADD
                CONSTRAINT FK_A65A946F4BBC2705 FOREIGN KEY (version_id) REFERENCES version (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE version_keyword ADD PRIMARY KEY (id)
        SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            ALTER TABLE version_keyword DROP CONSTRAINT FK_A65A946F4BBC2705
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE version_keyword DROP CONSTRAINT FK_A65A946F115D4552
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE version_keyword DROP CONSTRAINT version_keyword_pkey
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE version_keyword DROP id
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE version_keyword DROP index
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
                version_keyword
            ADD
                CONSTRAINT fk_a65a946f4bbc2705 FOREIGN KEY (version_id) REFERENCES version (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
                version_keyword
            ADD
                CONSTRAINT fk_a65a946f115d4552 FOREIGN KEY (keyword_id) REFERENCES keyword (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE version_keyword ADD PRIMARY KEY (version_id, keyword_id)
        SQL);
    }
}
