<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20250910105944 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create distribution table';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE distribution (created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_modified_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, reference VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, released_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, resolved_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, source TEXT DEFAULT NULL, version_id INT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX UNIQ_A44837814BBC2705AEA349138CDE5729 ON distribution (version_id, reference, type)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_A44837814BBC2705 ON distribution (version_id)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE distribution ADD CONSTRAINT FK_A44837814BBC2705 FOREIGN KEY (version_id) REFERENCES version (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            ALTER TABLE distribution DROP CONSTRAINT FK_A44837814BBC2705
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE distribution
        SQL);
    }
}
