parameters:
  kernel_secret: '%env(default:kernel_secret_file:KERNEL_SECRET)%'
  kernel_secret_file: '%env(default::file:KERNEL_SECRET_FILE)%'

dirigent:
  encryption:
    private_key: '%env(DECRYPTION_KEY)%'
    private_key_path: '%env(DECRYPTION_KEY_FILE)%'
    public_key: '%env(ENCRYPTION_KEY)%'
    public_key_path: '%env(ENCRYPTION_KEY_FILE)%'

framework:
  secret: '%kernel_secret%'

  messenger:
    transports:
      async:
        dsn: 'doctrine://default?auto_setup=0'

  trusted_proxies: '%env(TRUSTED_PROXIES)%'
  trusted_headers: ['x-forwarded-for', 'x-forwarded-host', 'x-forwarded-port', 'x-forwarded-prefix', 'x-forwarded-proto']

doctrine:
  dbal:
    url: 'postgresql://dirigent@127.0.0.1:5432/dirigent?serverVersion=16&charset=utf8'
