parameters:
  kernel_secret: '%env(default:kernel_secret_file:KERNEL_SECRET)%'
  kernel_secret_file: '%env(default::file:KERNEL_SECRET_FILE)%'

framework:
  secret: '%kernel_secret%'

  trusted_proxies: '%env(TRUSTED_PROXIES)%'
  trusted_headers: ['x-forwarded-for', 'x-forwarded-host', 'x-forwarded-port', 'x-forwarded-prefix', 'x-forwarded-proto']
