name: Build image

on:
  pull_request:
  push:

jobs:
  build-image:
    name: Test Docker build
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      -
        name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
