name: Test Docker build

on:
  pull_request:
  push:
    branches-ignore:
      - main
      - develop

jobs:
  test-build:
    name: Test Docker build
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out repo
        uses: actions/checkout@v4

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      -
        name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: false
          platforms: linux/amd64,linux/arm64
