name: Build images

on:
  pull_request:
  push:
  schedule:
    - cron: "30 4 * * *"

jobs:
  build-standalone:
    name: Standalone images

    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - name: Build images
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
